services:
  postgres:
    image: postgres:16-alpine
    container_name: tht-postgres
    environment:
      POSTGRES_USER: tht
      POSTGRES_PASSWORD: tht123
      POSTGRES_DB: tht_payment
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
